### ISSUE TITLE
Cannot found config file while init

### ISSUE THREAD

**Issue by CrabSAMA** [reeli/swagger-faker#8]
When I global install, and run `swagger-init`, it will throw a error:
.config/yarn/global/node_modules/swagger-faker/dist/lib/index.js:36
        throw new Error(ERROR_MESSAGES.NOT_FOUND_CONFIG_FILE);
        ^

Error: Cannot found config file swagger-faker.config.json
    at readSwaggerFakerConfig (/Users/crab.huang/.config/yarn/global/node_modules/swagger-faker/dist/lib/index.js:36:15)
    at Object.<anonymous> (/Users/crab.huang/.config/yarn/global/node_modules/swagger-faker/dist/lib/index.js:486:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/crab.huang/.config/yarn/global/node_modules/swagger-faker/bin/cli.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by reeli** [comment]
@CrabSAMA This issue has been fixed. Please install the latest version and try again.

**Comment by CrabSAMA** [comment]
Thanks~
